# Generated by Django 5.0.1 on 2024-03-18 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Judge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=20)),
                ("primary", models.CharField(max_length=100, verbose_name="name")),
                (
                    "secondary",
                    models.CharField(max_length=100, verbose_name="university"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Performer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=20)),
                ("primary", models.CharField(max_length=100, verbose_name="name")),
                (
                    "secondary",
                    models.CharField(max_length=100, verbose_name="university"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=20)),
                ("primary", models.CharField(max_length=100, verbose_name="name")),
                ("secondary", models.CharField(max_length=100, verbose_name="role")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=20)),
                ("primary", models.CharField(max_length=100, verbose_name="title")),
                (
                    "secondary",
                    models.CharField(default="", editable=False, max_length=100),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=20)),
                ("primary", models.CharField(max_length=100, verbose_name="name")),
                (
                    "secondary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song",
                        to="l3rd.performer",
                        verbose_name="performer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
