# Generated by Django 5.0.1 on 2024-03-18 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("l3rd", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="primary",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="song",
                to="l3rd.performer",
                verbose_name="performer",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="secondary",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
    ]
